### ISSUE TITLE
Hackathon114: SUIT Parameter for manifest sequence number?

### ISSUE THREAD

**Issue by dthaler** [suit-wg/manifest-spec#64] opened 2022-07-24 01:01 UTC
(This is actually an issue for https://github.com/bremoran/suit-update-management but that repo doesn't seem to allow filing issues, just pull requests)

The[ SUIT Reports spec](https://www.ietf.org/archive/id/draft-ietf-suit-report-02.html) allows
```
system-property-claims = {
  system-component-id => SUIT_Component_Identifier,
  + SUIT_Parameters,
}
```
But SUIT_Parameters was originally defined without any version parameter being specified.
draft-ietf-suit-update-management-00 section 4.4 adds suit-parameter-version which is a component
version number but not a manifest sequence number. That may be sufficient for policies that compare a component version number, but not policies that use a manifest sequence number.

If you want a policy (e.g., in TEEP or in any other software update server) that does something, like deploy a new version, if the latest manifest version wasn't used to boot, then this is cumbersome at present it seems.
Can draft-ietf-suit-update-management add a SUIT parameter for the manifest sequence number or is there another way to accomplish this more easily than using the component version number?

**Comment by bremoran** [comment] 2022-08-01 15:32
Because this is a reporting issue (reporting to a TAM, for example) it seems that it would make sense to address it in the suit-report draft.

The issue that I see here is that the SUIT Report is constructed in a "trusted" execution environment, such as a bootloader, or by a TEE when invoking a TA with a manifest. By reporting the digest, rather than the sequence number, we prevent a scenario where two manifests with identical sequence numbers (should not be permitted, but mistakes happen) are issued. It is possible that this scenario could be caused by a malicious TA Author--e.g. a malicious insider with access to the signing keys for a TA. By reporting the digest of the manifest, any possible ambiguity between maliciously or erroneously constructed manifests disappears.

Fundamentally, what I'm saying is that sequence numbers are unique by convention, whereas manifest digests are unique by construction. Conventions are subject to error or abuse. The manifest digest assertion is much stronger than the sequence number.

I appreciate the argument that it is easier for an unconstrained server to check whether the sequence number reported by a constrained TEE is within a range if it is the sequence number that is reported, however I would argue that the unconstrained server can quite happily look up the sequence number in a database if that is required.

Notwithstanding that, I see no problem adding a sequence number to the SUIT report, however I continue to believe that the digest should remain mandatory for the reasons outlined above.

We should migrate this issue to SUIT Report.

**Comment by hannestschofenig** [comment] 2023-07-07 07:25
Check: Has this issue been addressed in SUIT report?

**Closed** 2024-02-05 14:36 UTC
